# Generated by Django 5.2.5 on 2026-09-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('audience', 'Audience')], default='audience', max_length=20),
        ),
    ]
